"""Fixes from Bitbucket PR feedback: single Summary heading, annotation note
placement and wording, headline counts, identity-failure visibility, and the
dismiss help line."""

from __future__ import annotations

import json
import logging

import httpx
import pytest

from ai_pr_review.findings.models import Finding
from ai_pr_review.vcs._body import SLASH_COMMANDS_DOC_URL, strip_leading_summary_heading
from ai_pr_review.vcs.bitbucket import (
    BitbucketConfig,
    BitbucketProvider,
    _extract_walkthrough,
    _render_combined_body,
)
from ai_pr_review.vcs.http import RecordingClient, RetryPolicy, TapeRecorder
from ai_pr_review.vcs.marker import SUMMARY_MARKER_PREFIX, build_summary_marker
from ai_pr_review.vcs.protocol import DiffContext

_HEAD = "abc1234def5678abc1234def5678abc1234def56"
_BOT = "bot-account"
_DIFF = """diff --git a/app.py b/app.py
--- a/app.py
+++ b/app.py
@@ -1,3 +1,6 @@
 context_line_1
 context_line_2
 context_line_3
+added_line_4
+added_line_5
+added_line_6
"""


def _finding(text: str = "sql injection", *, ood: bool = False, sev: str = "High") -> Finding:
    return Finding(
        severity="Low" if ood else sev, confidence=90, finding=text,
        file="app.py", line=4, out_of_diff=ood,
    )


def _render(**kw: object) -> str:
    base: dict[str, object] = dict(
        existing_body=f"{build_summary_marker('abc', hidden=True)}\nFirst",
        findings=[_finding()], event="REQUEST_CHANGES", failed_agents=[],
        agent_prompt="", id_map={}, prior_id_map={}, workspace="ws",
        repo_slug="repo", head_sha=_HEAD,
    )
    base.update(kw)
    return _render_combined_body(**base)  # type: ignore[arg-type]


# --- Fix 1: doubled Summary heading ---------------------------------------


@pytest.mark.parametrize(
    "text",
    ["## Summary\n\nBody", "### Summary\nBody", "# Summary:\n\nBody", "## **Summary**\n\nBody"],
)
def test_strip_leading_summary_heading_any_level(text: str) -> None:
    assert strip_leading_summary_heading(text) == "Body"


def test_strip_leading_summary_heading_leaves_other_text() -> None:
    assert strip_leading_summary_heading("Intro\n## Summary\nBody") == "Intro\n## Summary\nBody"
    assert strip_leading_summary_heading("## Summary of changes\nBody") == "## Summary of changes\nBody"
    assert strip_leading_summary_heading("Body only") == "Body only"
    # Only one heading is removed.
    assert strip_leading_summary_heading("## Summary\n## Summary\nB") == "## Summary\nB"


def test_first_run_body_renders_one_summary_heading() -> None:
    first_run = f"{build_summary_marker('abc', hidden=True)}\n## Summary\n\nAdds foo.\n\n---\n*AI Review — generated by x*"
    body = _render(existing_body=first_run)
    assert "### Summary\nAdds foo." in body
    assert "## Summary" not in body.replace("### Summary", "")


def test_already_posted_doubled_heading_heals_on_next_run() -> None:
    doubled = (
        f"{build_summary_marker('abc', hidden=True)}\n## AI Review Findings\n\n"
        "**Findings:** 1\n\n### Findings\n- x\n\n### Summary\n## Summary\n\nAdds foo.\n"
    )
    assert _extract_walkthrough(doubled) == "Adds foo."
    body = _render(existing_body=doubled)
    assert body.count("Summary") == 1


# --- Fix 2: annotation note --------------------------------------------------


@pytest.mark.parametrize(
    ("count", "verb"), [(1, "is"), (2, "are")]
)
def test_annotation_note_after_list_plural_and_verb(count: int, verb: str) -> None:
    body = _render(annotated_count=count)
    note = f"{count} of the findings listed here {verb} also shown as inline Code Insights"
    assert note in body
    assert "above" not in body
    assert body.index("sql injection") < body.index(note)
    assert body.index("### Findings") < body.index(note)


def test_annotation_note_not_carried_into_walkthrough() -> None:
    body = _render(annotated_count=1, existing_body=(
        f"{build_summary_marker('abc', hidden=True)}\n## Summary\n\nAdds foo."
    ))
    assert _extract_walkthrough(body) == "Adds foo."


# --- Fix 3: headline counts --------------------------------------------------


def test_headline_shows_both_counts_with_out_of_diff_findings() -> None:
    findings = [_finding("in diff"), _finding("old issue", ood=True)]
    body = _render(findings=findings)
    assert "**Findings:** 1 in the diff, 2 total" in body


def test_headline_plain_count_without_out_of_diff() -> None:
    assert "**Findings:** 1\n" in _render() + "\n" or "**Findings:** 1" in _render()
    assert "total" not in _render().split("### Findings")[0]


# --- Fix 4 and 5: provider-level --------------------------------------------


def _provider(
    *,
    user_status: int = 200,
    verdicts: bool = False,
    post_response: httpx.Response | None = None,
    existing_comments: bool = True,
    user_response: httpx.Response | None = None,
) -> tuple[BitbucketProvider, dict]:
    captured: dict = {}
    created: dict = {}
    existing = {
        "id": 100,
        "content": {"raw": f"{SUMMARY_MARKER_PREFIX} sha={_HEAD} -->\n## Summary\n\nAdds foo."},
        "user": {"account_id": _BOT},
    }

    def handler(req: httpx.Request) -> httpx.Response:
        path = req.url.path.rstrip("/")
        if req.method == "GET" and path.endswith("/user"):
            if user_response is not None:
                return user_response
            if user_status >= 400:
                return httpx.Response(user_status, text="forbidden")
            return httpx.Response(200, json={"account_id": _BOT})
        if req.method == "GET" and path.endswith("/comments/101"):
            return httpx.Response(200, json=created)
        if req.method == "GET":
            return httpx.Response(200, json={"values": [existing] if existing_comments else []})
        if req.method == "POST" and path.endswith("/comments") and post_response is not None:
            return post_response
        if req.method == "POST" and path.endswith("/comments"):
            # Fail-closed identity => no existing summary => a new comment.
            created.update(
                id=101, content={"raw": json.loads(req.content)["content"]["raw"]},
                user={"account_id": _BOT},
            )
            return httpx.Response(201, json=created)
        if req.method == "PUT" and "/comments/" in path:
            captured["body"] = json.loads(req.content)["content"]["raw"]
            return httpx.Response(200, json={"id": int(path.rsplit("/", 1)[1])})
        return httpx.Response(200, json={})

    client = RecordingClient(
        http=httpx.Client(
            transport=httpx.MockTransport(handler),
            base_url="https://api.bitbucket.org/2.0",
        ),
        recorder=TapeRecorder(record_dir=None),
        retry_policy=RetryPolicy(attempts=1, base_backoff=0, jitter=False, sleep=lambda _s: None),
    )
    prov = BitbucketProvider(
        config=BitbucketConfig(
            workspace="ws", repo_slug="repo", pr_id=7, email="x@y", api_token="t",
            verdicts=verdicts,
        ),
        client=client,
    )
    return prov, captured


def test_identity_failure_logs_warning_with_status_and_shows_notice(
    caplog: pytest.LogCaptureFixture,
) -> None:
    prov, captured = _provider(user_status=403)
    with caplog.at_level(logging.WARNING, logger="ai_pr_review.vcs.bitbucket"):
        summary = prov.post_summary("## Summary\n\nAdds foo.", _HEAD)
        assert summary.created
        result = prov.post_findings(
            [_finding()], DiffContext(diff_text=_DIFF, head_sha=_HEAD), event="COMMENT",
            summary_comment_id=summary.comment_id,
        )
        assert result.ok, result.error
    warnings = [r.getMessage() for r in caplog.records if "could not resolve the bot" in r.getMessage()]
    assert len(warnings) == 1
    assert "HTTP 403" in warnings[0]
    assert "Account:Read" in warnings[0]
    assert "Bot account not verified" in captured["body"]


def test_identity_failure_still_fails_closed() -> None:
    prov, _ = _provider(user_status=403)
    assert prov._list_summary_comments() == []


def test_identity_ok_has_no_warning_or_notice(caplog: pytest.LogCaptureFixture) -> None:
    prov, captured = _provider()
    with caplog.at_level(logging.WARNING, logger="ai_pr_review.vcs.bitbucket"):
        prov.post_findings(
            [_finding()], DiffContext(diff_text=_DIFF, head_sha=_HEAD), event="COMMENT"
        )
    assert not [r for r in caplog.records if "could not resolve the bot" in r.getMessage()]
    assert "Bot account not verified" not in captured["body"]


def test_dismiss_help_line_only_when_verdicts_enabled() -> None:
    prov_on, cap_on = _provider(verdicts=True)
    prov_on.post_findings([_finding()], DiffContext(diff_text=_DIFF, head_sha=_HEAD), event="COMMENT")
    assert "bitbucket-setup#dismissing-findings" in cap_on["body"]
    footer_at = cap_on["body"].index("\n---\n*AI Review")
    assert cap_on["body"].index("bitbucket-setup#dismissing-findings") < footer_at

    prov_off, cap_off = _provider(verdicts=False)
    prov_off.post_findings([_finding()], DiffContext(diff_text=_DIFF, head_sha=_HEAD), event="COMMENT")
    assert "dismissing-findings" not in cap_off["body"]


def test_slash_doc_url_lives_in_vcs_body_and_handlers_reuse_it() -> None:
    from ai_pr_review.slash import handlers

    assert handlers.SLASH_COMMANDS_DOC_URL == SLASH_COMMANDS_DOC_URL
    assert SLASH_COMMANDS_DOC_URL.endswith("/slash-commands")


# --- #990: scope errors keep the granted list ---------------------------------


def test_post_summary_scope_error_keeps_required_and_granted_scopes() -> None:
    body = {
        "type": "error",
        "error": {
            "message": "Your credentials lack one or more required privilege scopes.",
            "detail": {
                "required": ["read:pullrequest:bitbucket"],
                "granted": ["read:user:bitbucket", "read:repository:bitbucket"],
            },
        },
    }
    prov, _ = _provider(post_response=httpx.Response(403, json=body), existing_comments=False)
    result = prov.post_summary("## Summary\n\nAdds foo.", _HEAD)
    assert not result.ok
    assert "HTTP 403" in (result.error or "")
    assert "required scopes: read:pullrequest:bitbucket" in (result.error or "")
    assert "granted scopes: read:user:bitbucket, read:repository:bitbucket" in (result.error or "")


# --- #991: the identity warning and notice depend on the response -------------

_NO_SCOPES = {"type": "error", "error": {"message": "API Token provided has no Bitbucket scopes."}}
_BAD_EMAIL = {"type": "error", "error": {"message": "API token must be used with an atlassian registered email"}}
_SCOPE_403 = {
    "type": "error",
    "error": {
        "message": "Your credentials lack one or more required privilege scopes.",
        "detail": {"required": ["read:user:bitbucket"], "granted": ["read:repository:bitbucket"]},
    },
}


def _post_findings_with_user(user_response: httpx.Response) -> tuple[list[str], str]:
    """Run post_summary then post_findings and return (warnings, comment body)."""
    import logging as _logging

    records: list[str] = []

    class _Capture(_logging.Handler):
        def emit(self, record: _logging.LogRecord) -> None:
            records.append(record.getMessage())

    prov, captured = _provider(user_response=user_response, existing_comments=False)
    handler = _Capture(level=_logging.WARNING)
    log = _logging.getLogger("ai_pr_review.vcs.bitbucket")
    log.addHandler(handler)
    try:
        summary = prov.post_summary("Adds foo.", _HEAD)
        prov.post_findings(
            [_finding()], DiffContext(diff_text=_DIFF, head_sha=_HEAD), event="COMMENT",
            summary_comment_id=summary.comment_id,
        )
    finally:
        log.removeHandler(handler)
    warnings = [r for r in records if "could not resolve the bot" in r]
    return warnings, captured.get("body", "")


@pytest.mark.parametrize("body", [_NO_SCOPES, _BAD_EMAIL])
def test_identity_401_says_credentials_rejected_not_account_read(body: dict) -> None:
    warnings, comment = _post_findings_with_user(httpx.Response(401, json=body))
    assert len(warnings) == 1
    assert "HTTP 401" in warnings[0]
    assert body["error"]["message"] in warnings[0]
    assert "rejected the credentials" in warnings[0]
    assert "lacks the Account:Read" not in warnings[0]
    assert "Bot account not verified" in comment
    assert "rejected the credentials (HTTP 401)" in comment
    assert "lacks the Account:Read" not in comment


def test_identity_403_names_account_read_and_shows_scope_lists() -> None:
    warnings, comment = _post_findings_with_user(httpx.Response(403, json=_SCOPE_403))
    assert "HTTP 403" in warnings[0]
    assert "lacks the Account:Read scope" in warnings[0]
    assert "required scopes: read:user:bitbucket" in warnings[0]
    assert "granted scopes: read:repository:bitbucket" in warnings[0]
    assert "lacks the Account:Read scope" in comment


def test_identity_500_has_neither_scope_advice() -> None:
    warnings, comment = _post_findings_with_user(httpx.Response(500, text="upstream down"))
    assert "HTTP 500" in warnings[0]
    assert "upstream down" in warnings[0]
    assert "cause is not clear" in warnings[0]
    assert "Account:Read" not in warnings[0]
    assert "cause is not clear" in comment


@pytest.mark.parametrize(
    ("response", "needle"),
    [
        (httpx.Response(200, text="<html>not json</html>"), "returned non-JSON"),
        (httpx.Response(200, json={"nickname": "bot"}), "had no account_id"),
    ],
)
def test_identity_bad_success_body_uses_generic_advice(response: httpx.Response, needle: str) -> None:
    warnings, comment = _post_findings_with_user(response)
    assert needle in warnings[0]
    assert "cause is not clear" in warnings[0]
    assert "Bot account not verified" in comment
